// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import domain "signIn/gateway/domain"
import mock "github.com/stretchr/testify/mock"

// FbRepository is an autogenerated mock type for the FbRepository type
type FbRepository struct {
	mock.Mock
}

// SendSignInRequest provides a mock function with given fields: _a0, _a1
func (_m *FbRepository) SendSignInRequest(_a0 context.Context, _a1 domain.AccessData) (domain.FbResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 domain.FbResponse
	if rf, ok := ret.Get(0).(func(context.Context, domain.AccessData) domain.FbResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(domain.FbResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, domain.AccessData) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
