
version: "3.8"

services:
  frontEnd:
    image: golang:1.15.6-alpine
    container_name: signIn_frontEnd 
    networks:
      - dev 
    labels:
      - "traefik.http.routers.frontEnd.rule=Host(`${SIGN_IN_FRONT_END_HOST}`)"
      - "traefik.http.services.frontEnd-frontEnd.loadbalancer.server.port=80"
      - "traefik.enable=true"
    working_dir: /service
    volumes:
      - .:/service
    entrypoint: go run main.go
    restart: always
networks:
  dev:
    external: true