kind: pipeline
type: docker
name: signIn

clone:
  disable: true

steps:
  - name: sign-build
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: drone_ssh_host
      user:
        from_secret: drone_ssh_user
      port:
        from_secret: drone_ssh_port
      key:
        from_secret: drone_ssh_key
      script:
        - cd ~/signIn
        - git checkout . && git checkout dev && git pull origin dev
        - docker-compose -f ./gateway/docker-compose.yml --env-file ./gateway/.env up -d --force-recreate
        - docker-compose -f ./frontEnd/docker-compose.yml --env-file ./frontEnd/.env up -d --force-recreate
        # - cd ../line
        # - docker-compose up -d --force-recreate
    when:
      branch:
        - dev

trigger:
  branch:
    - dev
  event:
    - push
