kind: pipeline
type: docker
name: test-gateway

steps:
  - name: test
    image: golang
    commands:
      - cd gateway/
      - go build
      - go test ./...

---

kind: pipeline
type: docker
name: test-line

steps:
  - name: test
    image: golang
    commands:
      - cd line/
      - go build
      - go test ./...

---

kind: pipeline
type: docker
name: test-fb

steps:
  - name: test
    image: golang
    commands:
      - cd fb/
      - go build
      - go test ./...

---

kind: pipeline
type: docker
name: signIn

steps:
  - name: sign-build
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: drone_ssh_host
      user:
        from_secret: drone_ssh_user
      port:
        from_secret: drone_ssh_port
      key:
        from_secret: drone_ssh_key
      script:
        - cd ~/signIn
        - git checkout . && git checkout dev && git pull origin dev
        - docker-compose -f ./gateway/docker-compose.yml --env-file ./gateway/.env up -d --force-recreate
        - docker-compose -f ./frontEnd/docker-compose.yml --env-file ./frontEnd/.env up -d --force-recreate
        - docker-compose -f ./line/docker-compose.yml --env-file ./line/.env up -d --force-recreate
        - docker-compose -f ./fb/docker-compose.yml --env-file ./fb/.env up -d --force-recreate
    when:
      branch:
        - dev

depends_on:
  - test-gateway
  - test-line
  - test-fb

trigger:
  branch:
    - dev
  event:
    - push