openapi: 3.0.0
info:
  title: Sign In Project
  description: 一個簡單的第三方驗證整合專案，以golang實現，依照各大平台Oauth2驗證流程，取得使用者的會員ID、使用名稱、email等資料，並回傳固定格式。
  version: 1.0.0

paths:
  /:
    post:
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                method:
                  type: string
                  description: 'line or google or fb'
                verifyCode:
                  type: string
                  description: '授權碼'
      responses:
        '200':
          content:
            application/json:
              schema:
						type:
						propterties:
								id:
								  type: string
								name:
								  type: string
								email:
								  type: string
                phone:
                  type: string
                extra:
                  type: string
                  description: 所有使用者資訊的json字串，包含access token等。