entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: devResolver 
        domains:
          - main: "your.domain.com"
providers:
  docker:
    endpoint: "unix://var/run/docker.sock"

certificatesResolvers:
  devResolver:
    acme:
      email: your.email@test.com 
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web