// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "signIn/google/domain"
import mock "github.com/stretchr/testify/mock"

// GetAccessTokenRepository is an autogenerated mock type for the GetAccessTokenRepository type
type GetAccessTokenRepository struct {
	mock.Mock
}

// GetAccessToken provides a mock function with given fields: _a0
func (_m *GetAccessTokenRepository) GetAccessToken(_a0 string) (domain.GetAccessTokenResponse, error) {
	ret := _m.Called(_a0)

	var r0 domain.GetAccessTokenResponse
	if rf, ok := ret.Get(0).(func(string) domain.GetAccessTokenResponse); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.GetAccessTokenResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
