
version: "3.8"

services:
  line:
    image: golang:1.15.6-alpine
    container_name: signIn_line
    networks:
      - dev 
    labels:
      - "traefik.http.routers.line.rule=Host(`${SIGN_IN_LINE_HOST}`)"
      - "traefik.http.services.line-line.loadbalancer.server.port=80"
      - "traefik.enable=true"
    working_dir: /service
    volumes:
      - .:/service
    entrypoint: go run main.go
    restart: always
networks:
  dev:
    external: true